"""add structured incident

Revision ID: 35b8ef589d2a
Revises: 988b7fcc5a6b
Create Date: 2026-06-27 16:58:39.364269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b8ef589d2a'
down_revision = '988b7fcc5a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('incident_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('criticality_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('criticality_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('ml_confidence')
        batch_op.drop_column('ml_emergency_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_emergency_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('ml_confidence', sa.FLOAT(), nullable=True))
        batch_op.drop_column('criticality_name')
        batch_op.drop_column('criticality_level')
        batch_op.drop_column('incident_name')
        batch_op.drop_column('incident_category')

    # ### end Alembic commands ###
