"""analytics dashboard fields

Revision ID: 988b7fcc5a6b
Revises: 
Create Date: 2026-06-22 00:01:23.854967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988b7fcc5a6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('campus_zone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hostel', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('weather_condition', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('response_time_minutes', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('response_time_minutes')
        batch_op.drop_column('temperature')
        batch_op.drop_column('weather_condition')
        batch_op.drop_column('hostel')
        batch_op.drop_column('campus_zone')
        batch_op.drop_column('incident_category')

    # ### end Alembic commands ###
